### ISSUE TITLE
INPUT_ variables need to be all uppercase to work

### ISSUE THREAD

**Issue by e110c0** [un-ts/changesets-gitlab#102]
when setting INPUT_ variables, the documentation states those variables are case insensitive. Turns out, they aren't `INPUT_title` is not working, only `INPUT_TITLE` is. Same for all other INPUT_ variables.

**Comment by JounQin** [comment]
You're right here

https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/core/src/core.ts#L128

Could you raise a PR to fix the typo?
