### ISSUE TITLE
Adding pre-release to pr

### ISSUE THREAD

**Issue by fbritoferreira** [un-ts/changesets-gitlab#104]
Changesets have a pre-release feature
https://github.com/changesets/changesets/blob/main/docs/prereleases.md 

Would it be possible to add this?

At the moment having to do it manually can be hard to get it right, maybe have a pre-release command?

Happy to work on this

**Comment by JounQin** [comment]
This package is just a replacement of changesets' GitHub Action for GitLab, it should not affect `changeset pre` commands?

https://github.com/un-ts/changesets-gitlab/blob/main/src/readChangesetState.ts#L18
