### ISSUE TITLE
Release merge request triggers pipelines without jobs

### ISSUE THREAD

**Issue by thomasaull** [un-ts/changesets-gitlab#117]
I have a weird issue, where when running `changeset-gitlab` there are two pipelines created without jobs which fail immediately. It happens when using for `GITLAB_TOKEN`:
- A personal access token of a newly created accout
- A project access token

But not if I use a personal access token of my regular account. For the projekt access token the `api` scope is used. For the newly created account all roles etc. are set like my regular account. It‘s really weird and I don‘t know why this happens.

Screenshots of the pipelines:
![image](https://github.com/un-ts/changesets-gitlab/assets/227756/4082e4d8-d0e8-4d84-98aa-399d9bd43e2f)

![image](https://github.com/un-ts/changesets-gitlab/assets/227756/4a552d6b-7100-4c80-a1a2-e042a36178bd)

**Comment by JounQin** [comment]
I have no idea what is going on neither, maybe request GitLab's service help?

**Comment by JounQin** [comment]
close due to lack of response.

**Comment by thomasaull** [comment]
@JounQin Sorry for some reason I did not get or missed a notification about your response. I understand the issues is probably not related to `changeset-gitlab` and I'm using a workaround now to mitigate this.

**Comment by JounQin** [comment]
@thomasaull If you could share your case and workaround for anyone else, that would be great.

**Comment by thomasaull** [comment]
@JounQin I'ts a pretty basic setup basically like the examples in your Readme. The workaround for me is to just use a Personal Access Token of my account.

**Comment by JounQin** [comment]
👌🏻
