### ISSUE TITLE
[Feature Request] Exception details

### ISSUE THREAD

**Issue by kriakiku** [un-ts/changesets-gitlab#122]
Hi! In the process of configuring CI/CD, I encountered exceptions. All network errors are not very informative:

```
🦋  Creating git tag...
🦋  New tag:  @***/***@0.0.5
[command]/usr/bin/git push origin --tags
To https://gitlab.com/***/***/***.git
 * [new tag]         @***/***@0.0.5 -> @***/***@0.0.5
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/builds/***/***/***/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 169332[73](https://gitlab.com/***/***/***/-/jobs/0000000000#L73)1[77](https://gitlab.com/***/***/***/-/jobs/0000000000#L77)94,
    socket: 1693327317796,
    lookup: 1693327317799,
    connect: 169332731[78](https://gitlab.com/***/***/***/-/jobs/0000000000#L78)02,
    secureConnect: 1693327317810,
    upload: 1693327317811,
    response: 169332731[80](https://gitlab.com/***/***/***/-/jobs/0000000000#L80)64,
    end: 1693327318067,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 3,
      tcp: 3,
      tls: 8,
      request: 1,
      firstByte: 253,
      download: 3,
      total: 273
    }
  },
  description: '403 Forbidden'
}
error Command failed with exit code 1.
```

It is unclear which part of the process the problem occurred with. It would be cool to see the details about the error 👉👈

**Comment by JounQin** [comment]
Well, PR welcome.

**Comment by JounQin** [comment]
Related https://github.com/jdalrymple/gitbeaker/issues/2600

**Comment by jdalrymple** [comment]
The error has a cause object connected to it. In this cause object you can access the raw Response object from fetch, including all the connected instances methods for seeing more information about the request. 

I try to [parse out](https://github.com/jdalrymple/gitbeaker/blob/52ef0e622de304d98afb811f4937560edefd8889/packages/rest/src/Requester.ts#L74)  the actual error messages, but sometimes they are not caught depending on the format that is returned

**Comment by JounQin** [comment]
https://github.com/jdalrymple/gitbeaker/blob/52ef0e622de304d98afb811f4937560edefd8889/packages/rest/src/Requester.ts#L79-L86

@jdalrymple Thanks the codes here make a lot of sense to me for understanding the error structure.
