### ISSUE TITLE
Create MR with a custom target branch

### ISSUE THREAD

**Issue by lluiscab** [un-ts/changesets-gitlab#69]
Right now, the MR is created with the target branch being the same as the one that's running the CI.

In our case, we use a branch `dev` for development and we'd like to merge all changes into `main` using the MR that changeset created. Problem is as I said, the target branch is always `dev` as it's using `CI_COMMIT_REF_NAME`. Could an option be added to specify a custom target branch? (Similar to how changeset has a `baseBranch` configuration option for comparisons)

As this is a quite simple change, I'd be uo tp opening a PR with such changes, maybe with a new `INPUT_TARGET_BRANCH` env variable?

**Comment by JounQin** [comment]
It seems different with the original GitHub Action? Maybe it's worth to discuss this at https://github.com/changesets/action first?

**Comment by lluiscab** [comment]
See: https://github.com/changesets/action/issues/88#issuecomment-832542789

**Comment by JounQin** [comment]
@lluiscab 

Then PR welcome to see how simple the change is.

**Comment by lluiscab** [comment]
Is there any documentation on how to develop and test on this project? Even tho it seems to be an easy change to implement, I'd really like to test any changes before opening a PR

**Comment by JounQin** [comment]
Sorry, but no document yet. You can just raise the PR, then a codesandbox CI like https://github.com/un-ts/changesets-gitlab/pull/66#issuecomment-1275517349 would be available to test on your own repository.

**Comment by lluiscab** [comment]
Okay. I'll see if I can opena  PR today.

Regarding the implementation, it makes sense to want to use the `baseBranch` config option from `.changeset/config.json` but I have a fear that doing so might break current installations. The other option is to use a `INPUT_MR_TARGET_BRANCH` environment variable. Which one would you go for?

**Comment by JounQin** [comment]
A new env `INPUT_MR_TARGET_BRANCH` seems fine to me, as you said `baseBranch` can be just broken.
